name: myworkflow
on: 
   push:
     branches: [ main ]
jobs:  
 job1:
  uses: hirenrparghi/reuse/.github/workflows/myworkflow.yml@main
 job2:  
  runs-on: ubuntu-latest
  needs: job1
  steps:
    - name: get env
      run: |
        echo ${{ needs.job1.outputs.value }}
      
