name: myworkflow
on:
  workflow_dispatch:
jobs:  
 job1:
  uses: hirenrparghi/reuse/.github/workflows/myworkflow.yml@main
 job2:  
  runs-on: ubuntu-latest
  needs: job1
  steps:
    - name: get env
      run: |
        echo ${{ needs.job1.outputs.new_value }}
      
